### ISSUE TITLE
0.9.0 build doesn't include src/javascript/index.js in release

### ISSUE THREAD

**Issue by dkniffin** [ava-cassiopeia/simple-switch#29]
In `package.json`, the `main` entrypoint is listed as `src/javascript/index.js`. However, in the 0.9.0 release, it looks like that was converted to TS.

I'm using this package via jspm.io, which requires the file to already be in JS. Can you please add a compilation step to release, so that the published version has the JS file available?

**Comment by ava-cassiopeia** [comment]
Dunno how I missed this issue when you first filed it...a year and a half ago...but uh sorry!! Will fix!

**Comment by ava-cassiopeia** [comment]
Version 0.9.1&mdash;which I just released on NPM and here on GitHub&mdash;_should_ fix this issue I think, but please take a look and let me know if this is working correctly for you.

**Comment by ava-cassiopeia** [comment]
There's also v0.9.2 available now. I didn't think I would get to both fixes tonight but I ended up with more time than expected so two releases in close proximity, whoops..

Anyway, mentioning here so that you don't run `npm i -S a-simple-switch@0.9.1` and miss the extra SASS improvements in v0.9.2.

**Comment by dkniffin** [comment]
@ava-cassiopeia I tried to use the new version, but it still doesn't seem to work. I get the error `TypeError: SimpleSwitch.init is not a function`

I'm not 100% sure what the fix is, but this is a similar library that I'm using that also uses TS and it's working properly: https://github.com/jackocnr/intl-tel-input

My best guess without digging further is that you need `"esModuleInterop": true` or another TS config from here: https://github.com/jackocnr/intl-tel-input/blob/master/tsconfig.json

**Comment by ava-cassiopeia** [comment]
Aw darn, thanks for the hint though! Here's my attempt at a fix:

I've just released v0.9.4, please install that and see if it fixes your issue. This version includes the normal minified build file from before (if you're just dropping the file into a webserver) **and** special compiled-for-nodeJS variants of the code which don't have minification, should be import-able from other code, and as a bonus also include TS declaration files. To produce these, I used compiler settings very similar to the ones in intl-tel-input, so I'm hoping they work correctly.

I pointed the `main` field of the package at these new, NodeJS-optimized files so _hopefully_ it works for you, but do give it a try and let me know how that works for you.

**Comment by dkniffin** [comment]
@ava-cassiopeia It looks like that worked. Thanks!

**Comment by ava-cassiopeia** [comment]
Yessss!! Happy to help!
